### ISSUE TITLE
Possible memory leak in bank panel

### ISSUE THREAD

**Issue by Simperfy** [Arcanorum/dungeonz#116]
### Describe the bug

Closing bank panel using `ESC` key logs an error in react.

### To reproduce

1. Start dungeonz
2. Goto bank
3. withdraw any item
4. press ESC on keyboard

### Expected behaviour

No error.

### Notes

*Error log:*
![image](https://user-images.githubusercontent.com/28738855/114374005-c0257c00-9bb5-11eb-887a-66c418ffaea9.png)

### Screenshots

https://user-images.githubusercontent.com/28738855/114375188-016a5b80-9bb7-11eb-8525-ead45c4afc34.mp4

### Browser

Chrome Version 89.0.4389.114 (Official Build) (64-bit)

### Device

Ubuntu 20.04

**Comment by Arcanorum** [comment]
I have also noticed this a few times, but haven't been able to reproduce it reliably.
Following your reproduction steps doesn't cause it for me.

**Comment by Arcanorum** [comment]
I think I see what is causing this now: The animated number text.
It can be triggered in any way that a sub-component (i.e. ItemSlot) of the panel is unmounted *while playing a text animation*.
- Open any panel that has animated text on it (i.e. inventory weight on inventory/bank//crafting/shop panels).
- While the text is animating up to the target amount, close the panel (ESC, or close button, either works)
-  Get the error
