### ISSUE TITLE
[Critical Bug] Invisible player when joining simultaneously

### ISSUE THREAD

**Issue by Simperfy** [Arcanorum/dungeonz#119]
### Describe the bug

When two players join at the same time one of them will not be able to see the other player, while the other has no problem.

### To reproduce

1. Open two dungeonz instance in different tabs
2. Press "play" simultaneously

### Expected behaviour

Should be able to see the other player.

### Notes

I debug the server side, the data is being emitted correctly, this means that the bug is somewhere in the client side.

### Screenshots

https://user-images.githubusercontent.com/28738855/114533849-ecf29580-9c80-11eb-92fa-646635ed20c8.mp4

### Browser

Chrome Version 89.0.4389.114 (Official Build) (64-bit)

### Device

Ubuntu 20.04

**Comment by Arcanorum** [comment]
I have noticed this happening for other types of entities too (mobs, projectiles), not just players. This has always worked fine, so I think it is just something I might have broken recently, maybe during the loading screen work. Will have a look.

**Comment by Arcanorum** [comment]
I see what is going on...

The websocket event handlers that adds entities (i.e. other players) are only added once the Phaser game state is finished loading, as allowing those events to run before the game state is ready causes all kinds of problems.

But if a player is added to the world while another player client is not yet ready (still loading, and gameplay event handlers to add the new players is not yet added), then the client will have missed the event to add the other player.

I think this can be solved by adding some sort of log of any received websocket events, and if the incoming event is not a valid event, then it will store it until the loading is finished, then when the event handlers are added it can just re-run all of the missed events to fastforward their client to the current game world state.

**Comment by Arcanorum** [comment]
That fixed it.
