### ISSUE TITLE
Wiki and Reddit Developpment

### ISSUE THREAD

**Issue by Sebasflow23** [Arcanorum/dungeonz#146]
The wiki is outdated, and so is the reddit. If you need someone to do it, I can.

**Comment by Arcanorum** [comment]
Sure.

I haven't had time to learn how to the wiki editing tools work properly or go through and add everything that might be wanted in the wiki. Anyone can edit it, so if you want to change it then go ahead.
A problem I see is adding specific values for things (stats for mob and items), which may change a lot between updates, so I would like to find an API kind of solution for updating specific values within a wiki page, so people don't need to keep manually updating it.

I should probably start at least posting the update notes to the subreddit. I think I am too biased towards Discord, but I know reddit has worked well for other games for more extended feedback and UGC. Reddit is also great for SEO which would help the game get noticed more. I could make you a moderator.

**Comment by Sebasflow23** [comment]
> I haven't had time to learn how to the wiki editing tools work properly or go through and add everything that might be wanted in the wiki. Anyone can edit it, so if you want to change it then go ahead.
A problem I see is adding specific values for things (stats for mob and items), which may change a lot between updates, so I would like to find an API kind of solution for updating specific values within a wiki page, so people don't need to keep manually updating it.

Got it. I'll work on it when I have time.

> I should probably start at least posting the update notes to the subreddit. I think I am too biased towards Discord, but I know reddit has worked well for other games for more extended feedback and UGC. Reddit is also great for SEO which would help the game get noticed more. I could make you a moderator.

Alright! I'm u/Flowey23 on reddit, I'll try popularizing the game!
