### ISSUE TITLE
Chat message notification

### ISSUE THREAD

**Issue by Arcanorum** [Arcanorum/dungeonz#153]
### Task description
Currently there is no way to tell when a chat message is received while the chat box is closed.
This means that you need to keep it open all of the time to be aware of new messages and negates the point of having the option to close it to save GUI space.

A new message alert/notification icon should be added to the chat button that would show when a new unread message has been received.

### References/notes
Example notification status icon:
![chat-notification-icon](https://user-images.githubusercontent.com/9785268/127714170-3a433090-7e1f-49f9-ad5a-bd190e8a3f2f.png)
![image](https://user-images.githubusercontent.com/9785268/127714210-592e234e-3069-46a3-82e7-aaaeb476e4fa.png)
![image](https://user-images.githubusercontent.com/9785268/127714361-e0faf42d-a740-41f6-8ee9-c31bb944035e.png)
Chat button: https://github.com/Arcanorum/dungeonz/blob/master/client/src/components/game/gui/GUI.jsx#L139

### Acceptance criteria
- When a new chat message is received while the chat box is closed, a notification icon should appear on the open/close chat box button.
- When a new chat message is received while the chat box is open, no notification should be shown.
- When the chat box is opened (either by pressing the chat box button or pressing Enter to start a quick-chat) while the notification icon is shown, then the notification icon should then be hidden.

**Comment by brunowxd1** [comment]
PR #157.
