### ISSUE TITLE
Boss Buff

### ISSUE THREAD

**Issue by Sebasflow23** [Arcanorum/dungeonz#166]
### Category
- Balance 

### Feature description
Currently, all bosses are extremely easy to solo, all you need to do is spam vampire fang or make it so that it can't reach you and out-range it. To fix this, I propose adding attack patterns and giving bosses a huge HP boost, so many players are needed to defeat a boss.

**Comment by Arcanorum** [comment]
What do you mean by "attack patterns"?

**Comment by Sebasflow23** [comment]
> What do you mean by "attack patterns"?
Like for Blood Lord, he would shoot super blood staffs at you (no recoil damage) while trying to get close to you to finish you off with a fang. This would prevent hammering it to death easily.

**Comment by Arcanorum** [comment]
Some bosses (Master assassin, Great gnarl, Arch mage) do have attack their own unique abilities.

I need to rework the older bosses that don't have them and give them some too.

If you can think of specific ones for each boss it would be more useful to have discussion of them as their own issues (i.e. "Bandit leader special ability") than this general request.
