### ISSUE TITLE
Iron golem

### ISSUE THREAD

**Issue by Arcanorum** [Arcanorum/dungeonz#171]
### Task description
Mining is currently too risk free as an activity, and can be easily grinded in certain areas without hostile mobs nearby.

A new "golem" type of creature should be added. This would be a passive creature with high defence and a powerful melee attack that would become hostile towards players that mine from any nearby ore rocks.

This golem would be made from iron (other metal variants in other tickets), so should resemble the iron ore rocks somewhat.

### References/notes
Example rock elemental creature from the base DawnLike tileset.
![image](https://user-images.githubusercontent.com/9785268/131359358-4d1e1612-e359-4587-ad62-faeb2817aa5a.png)
DawnLike tileset: **https://github.com/Arcanorum/dungeonz/blob/master/server/map/DawnLike/Characters/Elemental0.png**

This would need to be a 4 direction animation (up, down, left, right) like most other creatures in the game, alternating between 1 -> 2 -> 1 -> 3 repeating.

#### Code
- A config for IronGolem should be added to the Mobs.yml config file.
- A config property should be added to the `ResourceNode` class called "guardedBy" which would be an array of mob types that become hostile to a player that starts gathering from it. Empty by default.
- A config property should be added to the `ResourceNode` class called "guardedRange" which would be a number of the tile range to check for any mobs that are of any of the types set in the "guardedBy" property. 4 by default. Would do nothing if "guardedBy" is not set.
- A property should be added to each of the IronOre, DungiumOre, AgoniteOre, and NoctisOre configs in ResourceNodes.yml config setting the "guardedBy" property to "IronGolem".
- The `startGathering` method on the `ResourceNode` class should be modified to include a check for any mobs within the range of "guardedRange" that are of any type listed in "guardedBy", and set their `target` to be the player interacting with the resource node.

#### Visual
- 3 animation frames for each direction (up, down, left, right (left but flipped)), to be played in the basic humanoid animation pattern used by other entities: 1 (standing), 2 (right step), 1 (standing), 3 (left step), repeating.
- Expected files:
iron-golem-up-1.png
iron-golem-up-2.png
iron-golem-up-3.png
iron-golem-down-1.png
iron-golem-down-2.png
iron-golem-down-3.png
iron-golem-left-1.png
iron-golem-left-2.png
iron-golem-left-3.png
iron-golem-right-1.png
iron-golem-right-2.png
iron-golem-right-3.png

**Comment by Sebasflow23** [comment]
Golem summoning that uses up ores and a special scroll?

**Comment by Arcanorum** [comment]
> Golem summoning that uses up ores and a special scroll?

I guess. Make a feature request for it if you think so.

**Comment by Arcanorum** [comment]
Added to update 12.
