### ISSUE TITLE
Dash

### ISSUE THREAD

**Issue by Sebasflow23** [Arcanorum/dungeonz#175]
### Category
- Other

### Feature description
When player right clicks, player dashes in direction of to mouse. Dash is 4 blocks long, with 3 second cooldown.

### Notes

Idea from lastmagestanding.com

**Comment by Arcanorum** [comment]
What about on mobile devices with no right click?

I had an idea about something like this recently.
It would be a spell scroll you can equip and cast in any direction that would push you several tiles in that direction.
Something wind themed, like "Scroll of tailwind".

**Comment by Sebasflow23** [comment]
> What about on mobile devices with no right click?
> 
> I had an idea about something like this recently.
> It would be a spell scroll you can equip and cast in any direction that would push you several tiles in that direction.
> Something wind themed, like "Scroll of tailwind".

A scroll would be cool too, it would prevent traveling with the dash and encourage using it in fights.

**Comment by Arcanorum** [comment]
Closing in favour of the tailwind spell scroll added in update 12.
