### ISSUE TITLE
Hotbar item order persistence

### ISSUE THREAD

**Issue by brendan-c** [Arcanorum/dungeonz#180]
### Category
- UI 
- Other

### Feature description

When the a user logs out, the hotbar configuration (order or items within the hotbar) is saved. When the user logs in, that hotbar configuration is loaded.
### Notes

Currently, when a user logs out, the order of items within the hotbar is not saved. When a user logs in again, the hotbar is populated with items based upon the order of items within the inventory.

**Comment by Arcanorum** [comment]
Converted to task #181
