### ISSUE TITLE
Ice shard item

### ISSUE THREAD

**Issue by Arcanorum** [Arcanorum/dungeonz#188]
### Task description
A new material item type is needed for #185 and other potential ice related items.

### References/notes
Should look like a chunk of ice. Something like this:
![image](https://user-images.githubusercontent.com/9785268/133839280-f7e53e78-e0f8-4fda-a3e7-cace89a62182.png)

### Acceptance criteria
**Code**
- A new item config should be added to Items.yml called "IceShard".

**Visual**
- A GUI icon image. _icon-ice-shard.png_
- A pickup sprite image. _pickup-ice-shard.png_

**Comment by brendan-c** [comment]
Completed visual criteria 

A GUI icon image. icon-ice-shard.png - https://github.com/Arcanorum/dungeonz/commit/1450e9e5b06db8c647dce2f51b09e390a7076c8d

A pickup sprite image. pickup-ice-shard.png - https://github.com/Arcanorum/dungeonz/commit/d165278f5ce2e4e7f9bbde65fa7d5d3daa09b5bd

**Comment by brendan-c** [comment]
Completed code criteria

A new item config should be added to Items.yml called "IceShard" - https://github.com/Arcanorum/dungeonz/commit/8ffc4438d11e08d032a4b9a676384d4485430227

**Comment by brendan-c** [comment]
updated Items.yml -- changed IceShard `unitWeight` to `GenericMaterial` with https://github.com/Arcanorum/dungeonz/commit/738c8a65c914cbbfe0dbb2a09991d9195bffaa40

**Comment by Arcanorum** [comment]
Done.
