### ISSUE TITLE
Energy bar shake

### ISSUE THREAD

**Issue by Arcanorum** [Arcanorum/dungeonz#205]
### Task description
Currently it is too easy to run out of energy and not realise it, then wonder why the item you were using suddenly won't work.

An effect should be added to the energy bar on the GUI such that when an action is to be performed that costs energy, but the player doesn't have enough energy, that the bar shakes to bring attention to the energy status.

### References/notes
Health and energy meters component: https://github.com/Arcanorum/dungeonz/tree/master/client/src/components/game/gui/meters

Energy cost definition for each item (`useEnergyCost`):
https://github.com/Arcanorum/dungeonz/blob/master/server/src/configs/Items.yml
This data should be available on the client via the `ItemTypes` catalogue object which can be accessed via import.
i.e.
`import ItemTypes from "../ etc ../catalogues/ItemTypes.json";`
(see InventoryPanel.jsx for reference)

Example of not having enough energy when trying to use an item:
![not-enough-energy](https://user-images.githubusercontent.com/9785268/135719809-777d01a4-e240-430e-9e58-4e3972e46d69.gif)

### Acceptance criteria
- When a player attempts to use an item that they don't have enough energy to use, the energy meter should shake from side to side briefly then return to it's original position.

**Comment by javigaralva** [comment]
Anyone is working on this? I would like to take it. Thanks!

**Comment by Arcanorum** [comment]
> Anyone is working on this? I would like to take it. Thanks!

Yeah. Sometimes the assignee doesn't get updated some times.
The status column on the main board project (https://github.com/Arcanorum/dungeonz/projects/1) is usually the best thing to check, as not everyone is on GitHub.

**Comment by javigaralva** [comment]
Oh... 😔
