### ISSUE TITLE
Public server down?

### ISSUE THREAD

**Issue by andrewkchan** [Arcanorum/dungeonz#229]
Sorry if this is the wrong place to report this. I'm interested in learning more about this project and possibly contributing, but it looks like the public server (https://test.rogueworld.io/) where I can actually play the game is down?

**Comment by Arcanorum** [comment]
It isn't running anywhere right now, so you would need to localhost to try it out I'm afraid.

I haven't had much free time lately to work on the project, as other paid work has been taking priority ツ.

**Comment by andrewkchan** [comment]
That was fast!

Thanks, I will check it out locally. I also just noticed there is a discord server.
