### ISSUE TITLE
Chat box

### ISSUE THREAD

**Issue by Arcanorum** [Arcanorum/dungeonz#39]
### Task description
A commonly requested feature is a persistent, and ideally global, way of chatting with other players.

This is a standard feature for MMO games and has been implemented a million times so nothing too radical is expected here.

Basic summary:
A way to communicate with other players over longer distances, and have messages remain viewable for longer in a chat log. Currently it is annoying to have to quickly read someones message, or miss some what what they said and they need to type it again, or have to keep opening another app like Discord to have a better chat experience.

#### Chat scopes
Basically channels/topics/categories for messages.
**Local**: Nearby players within view range.
**Global**: All players across all maps.
**Trade**: All players across all maps.
~~**Guild**: Guild members only.~~ (Future, not for right now)

#### Log
A chat log/history of previous messages is **not** needed to be kept on the server. Only messages that a client receives after they join the game will be what they can see and scroll back through.
A limit for the amount of messages kept in the client message history will be needed, after which the oldest messages will be popped off as new ones are received.

#### Limiting
Players/bots that spam messages will show up at some point, so a limit of how many messages a client can send in a given time will be needed e.g. 15 messages per minute, after which they must wait a few seconds to chat again. Higher limit = Allows more messages in the same amount of time.
This limit should be server configurable for each chat scope.
- **Trade**: Lowest limit, as it is available to everyone, and should be used for players looking to find/buy/sell things, and not for extended chatting.
- **Global**: Lower limit, as it is visible to everyone, and more players in total would be chatting into that scope at once.
- **Local**: Higher limit, as it will be received by fewer other players, and would be mostly for players near each other having a conversation.
- **Guild**: Highest limit/no restriction, as it will be basically like a friends chat, that is limited to those who choose to be in the guild.

#### Filtering
I think censoring profanity is usually a pointless battle to try and fight. People always find creative ways of getting around filters, and those filters often just annoy everyone else. I know of games with strict filters to the point that common words get filtered, such as "assassin" censored for containing "ass", "knight" censored for containing "nig", etc.

I wouldn't want to remove the freedom of being able to say _"Oh shit!"_ when realising you made it out of a dungeon with 1HP left.

There are 2 viable solutions:
- Client side filtering. A player can choose a setting to turn on/off chat filtering for the messages they receive. Everyone else (such as the sender) sees the message as it is. Particularly useful for people making a video/streaming (or taking a screenshot) for their chat box to not get filled with things they don't want to be seen in whatever they are making.
- This game has the design potential to solve the problem of bad-mouthers in a more organic way, given that most of the game world is open PvP, those who make a bad name for themselves can expect to get hunted down, and that a lot of the content is collaborative (trading/dungeons/guilds in the future) which other players can choose not to include that other player in.

#### Interface wireframe
![chat-box-draft](https://user-images.githubusercontent.com/9785268/111249503-bbe06000-8603-11eb-9c8c-5e06fdda625d.png)

**Comment by Simperfy** [comment]
I would like to work on this feature but first please rename the database from "accounts" to "dungeonZ".
https://github.com/Arcanorum/dungeonz/projects/2#card-50256780

**Comment by Arcanorum** [comment]
> I would like to work on this feature but first please rename the database from "accounts" to "dungeonZ".
> https://github.com/Arcanorum/dungeonz/projects/2#card-50256780
> 
> To avoid possible conflicts in production.

The DB has been renamed to dungeonzDB.
