### ISSUE TITLE
[Question]: About moving to ReactJS

### ISSUE THREAD

**Issue by Simperfy** [Arcanorum/dungeonz#98]
### Background:
I'm currently exploring the latest updated branch which is feat/react.
Upon exploring I noticed that the GUI is still in progress of migration. (inside client2 folder)
I would like to contribute but wasn't able to do so as I didn't found any resources regarding the migration process.

### Question:
Where is the roadmap regarding the migration process from current setup to ReactJS?

**Comment by Arcanorum** [comment]
I was just going to do it myself as it was a large task with a lot of things being changed, so I figured it wasn't worth splitting up at this point until most of it was already done.

There are a few bits of the GUI left of the things I wanted migrating over, then this branch would become the base for the items rework work, as that will require creating new panels for (not just simple conversions of the existing ones) of the bank panel, crafting panel, shop panel, inventory panel, and inventory hotbar.

Now that I have a better idea of what is going to be involved, I'll create a project roadmap for the item rework and add those as tasks to it.

**Comment by Simperfy** [comment]
I see, right now I'm working at #99 and I'm trying to piece everything together based on your previous work.
Feedback would be highly appreciated especially with regards to the folder structure.

**Comment by Arcanorum** [comment]
The folder structure is a bit of a mess. There are a lot of parts that don't fit nicely together: Phaser related files, gameplay logic files, the React components, networking/event logic. I just organised them however I thought was OK at the time and was going to go through and tidy it up when I had a better understanding of all the parts and how they fit together.
So, the folder structure isn't well defined and can be changed.
